org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.native.cacheKind.iosArm64=none
android.useAndroidX=true

# Publishing
GROUP=io.github.kwmt.revenuecat
VERSION_NAME=0.0.9
mavenCentralPublishing=true
signAllPublications=true

POM_NAME=revenuecat-shared
POM_DESCRIPTION=A small Kotlin Multiplatform wrapper around the RevenueCat SDK for checking entitlements and making purchases on Android and iOS from shared code.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/kwmt/revenuecat-shared
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/kwmt/revenuecat-shared
POM_SCM_CONNECTION=scm:git:git://github.com/kwmt/revenuecat-shared.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/kwmt/revenuecat-shared.git
POM_DEVELOPER_ID=kwmt
POM_DEVELOPER_NAME=Yasutaka Kawamoto
POM_DEVELOPER_URL=https://github.com/kwmt
